#!/bin/bash
#only installs specified packages, if the refcount in $DOCKER_UTILS_APT_REF_COUNTS does not exist

set -ex

apt-touch-installed-refcounts

for var in "$@"
do
    if [[ ! "$var" =~ ^- ]]; then

    	PKG_REF_COUNT_PATH="$DOCKER_UTILS_APT_REF_COUNTS/$var"

    	PKG_REF_COUNT=1

    	if [ -f "$PKG_REF_COUNT_PATH" ]; then
    		PKG_REF_COUNT=$(expr $(cat "$var_ref_count_path") + 1)	
    	else
    		INSTALL_PKGS="$INSTALL_PKGS $var"
    	fi
		
		echo $PKG_REF_COUNT > "$PKG_REF_COUNT_PATH"

	else
		INSTALL_OPTS="$INSTALL_OPTS $var"
    fi
done

if [[ ! -z "$INSTALL_PKGS" ]]; then

	export DEBIAN_FRONTEND=noninteractive

	apt-get update

	apt-get install -y --no-install-recommends $INSTALL_OPTS $INSTALL_PKGS

	rm -rf /var/lib/apt/lists/*

fi