#!/bin/bash
#only purges if the refcount in $DOCKER_UTILS_APT_REF_COUNTS is lower than 1

set -ex

for var in "$@"
do
	PKG_REF_COUNT_PATH="$DOCKER_UTILS_APT_REF_COUNTS/$var"

    if [[ ! "$var" =~ ^- && -f "$PKG_REF_COUNT_PATH" ]]; then

		PKG_REF_COUNT=$(expr $(cat "$PKG_REF_COUNT_PATH") - 1)

    	if [[ $PKG_REF_COUNT < 1 ]]; then
			PURGE_PKGS="$PURGE_PKGS $var"

    		rm "$PKG_REF_COUNT_PATH"
    	else
			echo PKG_REF_COUNT > "$PKG_REF_COUNT_PATH"
    	fi
    else
    	PURGE_OPTS="$PURGE_OPTS $var"
    fi
done

if [[ ! -z "$PURGE_PKGS" ]]; then

	export DEBIAN_FRONTEND=noninteractive

	apt-get purge -y $PURGE_OPTS $PURGE_PKGS

	apt-get autoremove -y

fi