#!/bin/bash

set -ex

JETTY_TGZ_URL=https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/$JETTY_VERSION/jetty-distribution-$JETTY_VERSION.tar.gz

mkdir -p "$JETTY_BASE" "$JETTY_RUN" "$JETTY_TMPDIR"

chown -R jetty:jetty "$JETTY_RUN" "$JETTY_TMPDIR" "$JETTY_BASE"

apt-get-install curl gnupg

curl -L $JETTY_TGZ_URL > jetty.tar.gz

# 1024D/8FB67BAC 2006-12-10 Joakim Erdfelt <joakime@apache.org>
#B59B67FD7904984367F931800818D9D68FB67BAC 
# 1024D/D7C58886 2010-03-09 Jesse McConnell (signing key) <jesse.mcconnell@gmail.com>
#5DE533CB43DAF8BC3E372283E7AE839CD7C58886

gpg-verify 	$JETTY_TGZ_URL.asc \
			jetty.tar.gz \
			ha.pool.sks-keyservers.net:B59B67FD7904984367F931800818D9D68FB67BAC \
			ha.pool.sks-keyservers.net:5DE533CB43DAF8BC3E372283E7AE839CD7C58886

xtrct jetty.tar.gz

mv jetty-distribution-$JETTY_VERSION $JETTY_HOME

# Get the list of modules in the default start.ini and build new base with those modules, then add setuid
MODULES="$(grep -- ^--module= "$JETTY_HOME/start.ini" | cut -d= -f2 | paste -d, -s)"
java -jar "$JETTY_HOME/start.jar" --add-to-startd="$MODULES,setuid"

apt-get-purge curl gnupg