#!/bin/bash

set -ex

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

if [[ ! -f /etc/apt/sources.list.d/jessie-backports.list ]]; then
	echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
fi

apt-get-install \
        unzip \
        bzip2 \
        xz-utils \
        openjdk-8-jdk="$JAVA_DEBIAN_VERSION" \
        ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION"

/var/lib/dpkg/info/ca-certificates-java.postinst configure
